routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function (){

    Route::get('add-costing', ['uses'=>'CustomerController@dummyIndex', 'as'=>'users.index']); // =========Dummy
	
    Route::get('/','ProductController@dashboard');
    Route::post('/filterizedproduct', 'ProductCostingController@filterizedProduct')->name('filterizedproduct');
	// Route::get('/', function(){
	// 	return view('welcome');
	// });

    // Route::get('/', 'CustomerController@test');
    // Route::get('add-costing', 'ProductCostingController@index');

    Route::resource('customers','CustomerController');
    Route::get('customer/{id}/delete','CustomerController@remove');
    Route::post('/customer/update-status', 'CustomerController@statusUpdated');

    Route::resource('vendors','VendorController');
    Route::get('vendor/{id}/delete','VendorController@remove');
    Route::get('/product-data/{id}','ProductCostingController@getDetails');
    Route::post('/vendor/update-status', 'VendorController@statusUpdated');

    Route::post('/store-costing', 'ProductCostingController@storeCosting')->name('store-costing');

    Route::resource('boards','BoardController');
    Route::resource('grammage','GrammageController');
    Route::get('/board/{id}/delete', 'BoardController@remove');
    Route::get('/vendor/{id}/delete', 'VendorController@remove');
    Route::get('/customer/{id}/delete', 'CustomerController@remove');
    Route::get('/grammage/{id}/delete', 'GrammageController@remove');

    Route::resource('products','ProductController')->middleware('optimizeImages');
    Route::get('product-costing/{id}/history', 'ProductCostingController@updatedCosting');



    // Route::get('addcosting','ProductController@addCosting'); 
    // Route::get('store-costing','ProductController@storeCosting')->name('storeCosting'); 

    Route::get('/customer/{id}/get-product', 'ProductController@getProduct');
    Route::get('/product/{id}/details', 'ProductCostingController@getDetails');
    Route::get('/product-history/{id}/details', 'ProductCostingController@getUpdatedDetails');
    Route::get('/product/{id}/delete', 'ProductController@remove');

    Route::get('/product/{id}/edit', 'ProductCostingController@editCosting');
    //Profile
    Route::group(['prefix' => 'profile'], function (){
        Route::get('',function(){
            return view('profile.index');
        });
        Route::get('change-password',function(){
            return view('profile.change-password');
        });
        Route::post('change_password','Auth\ForgotPasswordController@changePassword')->name('change_password');
    });
	
});

app/Models/Vendors.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Vendors extends Model
{
     protected $fillable = [
		'name',
		'mobile',
		'email',
		'description',
	];

    public $table = "vendors";
}

app/Http/Controllers/VendorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Http\Controllers\Controller as Controller;
use App\Http\Requests\StoreAdRequest;
use App\Models\Vendors;
use App\Models\Product;
use App\User;
use Carbon\Carbon;
// use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use RealRashid\SweetAlert\Facades\Alert;
use App\DataTables\VendorsDataTable;
use Auth;

class VendorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(VendorsDataTable $dataTable)
    {
        return $dataTable->render('vendors.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('vendors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input=$request->all();
        Vendors::create($input);
        Alert::success('Vendor Created successfully');
        return redirect('vendors');
    }

    public function getAuthUser()
    {
        $vendor=User::where('id',Auth::id())->first();

        return $vendor;

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $vendor=Vendors::where('id',$id)->first();

        return view('vendors.edit',compact('vendor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Vendors::where('id',$request->vendor_id)->update(['name'=>$request->name,'email'=>$request->email,'mobile'=>$request->mobile,'description'=>$request->description]);
         Alert::success('Vendor updated successfully');
        return redirect('vendors');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
     public function remove($id)
    {
        Vendors::where('id',$id)->delete();
        Alert::success('Vendor deleted successfully');
        return redirect('vendors');

    }
     public function statusUpdated(Request $request)
    {

        $user=Vendors::where('id',$request->id)->update(['status'=>$request->status]);
       
        // Alert::success('Customer'.$request->status.'successfully');
        return $user;
    }

    public function getVendors()
    {
        $vendor=Vendors::all();

        return $vendor;
    }
    // public function remove($id)
    // {
    //     Vendors::where('id',$id)->delete();
    //     Alert::success('Vendor deleted successfully');
    //     return redirect('vendors');

    // }
}

resources/views/vendors/action.blade.php
<!-- <a href=""><i class="fas fa-eye" style="color: darkblue"></i></a> -->
<a href="{{ route('vendors.edit',$id) }}"><i class="fas fa-pen" style="color: brown"></i></a>

resources/views/vendors/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Create Vendor</h3>
            </div>
            <form method="post" action="{{ route('vendors.store') }}" enctype="multipart/form-data">
               @csrf
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Vendor Name</label>
                        <input name="name" placeholder="vendor name" class="form-control" type="text" required>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Mobile</label>
                        <input name="mobile" placeholder="Enter Phone No" class="form-control"
                        oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);"maxlength = "11" type="number" required>
                     </div>
                  </div>                 
               </div>
               <div class="row">
                  <!-- category_type --verified -->

                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Email</label>
                        <input name="email" placeholder="email" class="form-control" type="email" required>
                     </div>
                  </div>

                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                           <textarea name="description" class="form-control" placeholder="Description"></textarea>
                     </div>
                  </div>                 
               </div>              

               <button class="btn btn-success">Create</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/vendors/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Edit Vendor</h3>
            </div>
            <form method="POST" action="{{ route('vendors.update', $vendor->id) }}" enctype="multipart/form-data">
               {{csrf_field()}}
               {{method_field('PUT')}}
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>vendor Name</label>
                        <input name="name" placeholder="vendor name" value="{{$vendor->name}}" class="form-control" type="text" required>
                     </div>
                  </div>
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Mobile</label>
                        <input name="mobile" value="{{$vendor->mobile}}" placeholder="phone no" class="form-control" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" type = "number" maxlength = "11" required>
                     </div>
                  </div>                 
               </div>
               <div class="row">
                  <!-- category_type --verified -->

                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Email</label>
                        <input name="email" value="{{$vendor->email}}" placeholder="email" class="form-control" type="email" required>
                     </div>
                  </div>
                   <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                      <textarea name="description" class="form-control" placeholder="Description">{{ ucfirst($vendor->description) }}</textarea>  
                     </div>
                  </div> 
                   
               </div>            
                <input type="hidden" name="vendor_id" value="{{$vendor->id}}">
               <button class="btn btn-success">Update</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/vendors/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Vendors</h1>
@stop

@section('content')
    {{$dataTable->table()}}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
 <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>

     <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
{{$dataTable->scripts()}}


<script src="{{asset('js/axios.min.js')}}"></script>
    <script>
        $(document).ready(function (){

            window.LaravelDataTables["vendors-table"].on('draw', function(){
                $('.bt-toggle').bootstrapToggle();

            });
        })

        // send user's status update request
        function updateUserStatus(el){

            let id      = $(el).data('id');
           

            let status;

            if($(el).is(':checked')) {
                status = 'active';
            } else{
                status = 'deactivate';
            }

            if(id > 0){
                let url =  "/vendor/update-status"
                console.log(id)
                console.log(status)
                axios.post(url,{id: id, status: status})
                    .then(function(response){
                    	console.log(response.data)
                    	
                        if(response.data.error){
                              alertify.error('Error message');

                        }else{
                           alertify.success('vendor  '+status+'  successfully');

                        }
                    })
                    .catch(function(error){
                        console.log(error)
                    })
            }
        }
    </script>
@stop