routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function (){

    Route::get('add-costing', ['uses'=>'CustomerController@dummyIndex', 'as'=>'users.index']); // =========Dummy
	
    Route::get('/','ProductController@dashboard');
    Route::post('/filterizedproduct', 'ProductCostingController@filterizedProduct')->name('filterizedproduct');
	// Route::get('/', function(){
	// 	return view('welcome');
	// });

    // Route::get('/', 'CustomerController@test');
    // Route::get('add-costing', 'ProductCostingController@index');

    Route::resource('customers','CustomerController');
    Route::get('customer/{id}/delete','CustomerController@remove');
    Route::post('/customer/update-status', 'CustomerController@statusUpdated');

    Route::resource('vendors','VendorController');
    Route::get('vendor/{id}/delete','VendorController@remove');
    Route::get('/product-data/{id}','ProductCostingController@getDetails');
    Route::post('/vendor/update-status', 'VendorController@statusUpdated');

    Route::post('/store-costing', 'ProductCostingController@storeCosting')->name('store-costing');

    Route::resource('boards','BoardController');
    Route::resource('grammage','GrammageController');
    Route::get('/board/{id}/delete', 'BoardController@remove');
    Route::get('/vendor/{id}/delete', 'VendorController@remove');
    Route::get('/customer/{id}/delete', 'CustomerController@remove');
    Route::get('/grammage/{id}/delete', 'GrammageController@remove');

    Route::resource('products','ProductController')->middleware('optimizeImages');
    Route::get('product-costing/{id}/history', 'ProductCostingController@updatedCosting');



    // Route::get('addcosting','ProductController@addCosting'); 
    // Route::get('store-costing','ProductController@storeCosting')->name('storeCosting'); 

    Route::get('/customer/{id}/get-product', 'ProductController@getProduct');
    Route::get('/product/{id}/details', 'ProductCostingController@getDetails');
    Route::get('/product-history/{id}/details', 'ProductCostingController@getUpdatedDetails');
    Route::get('/product/{id}/delete', 'ProductController@remove');

    Route::get('/product/{id}/edit', 'ProductCostingController@editCosting');
    //Profile
    Route::group(['prefix' => 'profile'], function (){
        Route::get('',function(){
            return view('profile.index');
        });
        Route::get('change-password',function(){
            return view('profile.change-password');
        });
        Route::post('change_password','Auth\ForgotPasswordController@changePassword')->name('change_password');
    });
	
});

app/Models/Customers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
   protected $fillable = [
		'name',
		'company_name',
		'mobile',
		'email',
		'description',
	];

    public $table = "customers";
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Http\Controllers\Controller as Controller;
use App\Http\Requests\StoreAdRequest;
use App\Models\Customers;
use App\Models\Products;
use App\Models\Order;
use App\Models\BoardGramage;
use Carbon\Carbon;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use RealRashid\SweetAlert\Facades\Alert;
use App\DataTables\CustomersDataTable;
use App\Models\ProductCosting;

use DataTables;

use Illuminate\Support\Str; 

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(CustomersDataTable $dataTable)
    {
        return $dataTable->render('customers.index');
    }

    // public function dummyIndex(Request $request)
    // {
    //     if ($request->ajax()) {

              

    //         $data = ProductCosting::latest()->get();

   

    //         return Datatables::of($data)

    //                 ->addIndexColumn()

    //                 ->filter(function ($instance) use ($request) {

    //                     if (!empty($request->get('email'))) {

    //                         $instance->collection = $instance->collection->filter(function ($row) use ($request) {

    //                             return Str::contains($row['email'], $request->get('email')) ? true : false;

    //                         });

    //                     }
    //                     if (!empty($request->get('name'))) {

    //                         $instance->collection = $instance->collection->filter(function ($row) use ($request) {

    //                             return Str::contains($row['name'], $request->get('name')) ? true : false;

    //                         });

    //                     }

   

    //                     if (!empty($request->get('search'))) {

    //                         $instance->collection = $instance->collection->filter(function ($row) use ($request) {

    //                             if (Str::contains(Str::lower($row['email']), Str::lower($request->get('search')))){

    //                                 return true;

    //                             }else if (Str::contains(Str::lower($row['name']), Str::lower($request->get('search')))) {

    //                                 return true;

    //                             }

   

    //                             return false;

    //                         });

    //                     }

   

    //                 })

    //                 ->addColumn('action', function($row){

  

    //                        $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm">View</a>';

  

    //                         return $btn;

    //                 })

    //                 ->rawColumns(['action'])

    //                 ->make(true);

    //     }

    

    //     return view('customers.users');        
    // }

     public function dummyIndex(Request $request)
    {
        if ($request->ajax()) {

            $temp = DB::table("product_costing")
                ->join("products" , "product_costing.product_id", "=", "products.id")
                // ->where('ads.ad_status','=','pending')
                ->select('product_costing.*','products.customer_id','products.image as image','product_costing.id as temp','products.image as image','product_costing.is_proofing as proofing','product_costing.is_regular_board as board','product_costing.is_local as quality')
                ->orderBy('created_at','DESC')
                ->get();
             $data=[];   

            foreach ($temp as $key => $value) 
            {   
                $w_h = (array)$value;

                $w_h['product_id']=Helper::productIdToName($w_h['product_id']);
                $w_h['customer_id']=Helper::customerIdToCompany($w_h['customer_id']);
                $w_h['is_proofing']=Helper::proofingIdToName($w_h['is_proofing']);
                $w_h['is_regular_board']=Helper::boardToName($w_h['is_regular_board']);
                $w_h['is_local']=Helper::qualityIdToName($w_h['is_local']);
                array_push($data, $w_h);

            }

   

            return Datatables::of($data)

                    ->addIndexColumn()

                    ->filter(function ($instance) use ($request) {

                        if (!empty($request->get('product_id'))) {

                            $instance->collection = $instance->collection->filter(function ($row) use ($request) {

                                return Str::contains($row['product_id'], $request->get('product_id')) ? true : false;

                            });

                        }
                        if (!empty($request->get('proofing'))) {

                            $instance->collection = $instance->collection->filter(function ($row) use ($request) {

                                return Str::contains($row['proofing'], $request->get('proofing')) ? true : false;

                            });

                        }

                        if (!empty($request->get('customer_id'))) {

                            $instance->collection = $instance->collection->filter(function ($row) use ($request) {

                                return Str::contains($row['customer_id'], $request->get('customer_id')) ? true : false;

                            });

                        }

   

                        if (!empty($request->get('search'))) {

                            $instance->collection = $instance->collection->filter(function ($row) use ($request) {

                                if (Str::contains(Str::lower($row['product_id']), Str::lower($request->get('search')))){

                                    return true;

                                }else if (Str::contains(Str::lower($row['proofing']), Str::lower($request->get('search')))) {

                                    return true;

                                }else if (Str::contains(Str::lower($row['customer_id']), Str::lower($request->get('search')))) {

                                    return true;

                                }
                                
   

                                return false;

                            });

                        }

   

                    })

                    ->addColumn('action', function($row){

  

                           $btn ='<a href="/product/'.$row['temp'].'/details"><button class="btn btn-primary"value="'.$row['temp'].'">View</button></a>';



  

                            return $btn;

                    })
                    ->addColumn('edit', function($row){

  

                           $btn ='<a href="/product/'.$row['temp'].'/edit"><button class="btn btn-primary"value="'.$row['temp'].'">Edit</button></a>';
                            


  

                            return $btn;

                    })

                    ->addColumn('history', function($row){

                           $btn ='<a href="/product-costing/'.$row['temp'].'/history"><button class="btn btn-primary">History</button></a>';


                            return $btn;

                    })

                    ->addColumn('image', function ($row) { 
                          $url=asset($row['image']); 
                           return '<img src='.$url.' border="0" height="50" class="img-rounded img-responsive" align="center" />'; 
                    })
                    ->editColumn('proofing',function ($row){

                            switch(Helper::proofingIdToName($row['proofing'])){
                                case "Costing":
                                    $class = "bg-success";
                                    break;
                                case "Proofing":
                                    $class = "bg-info";
                                    break;
                                case "None":
                                    $class = "bg-primary";
                                    break;    
                            }

                        return '<span class="badge '.$class.'">'.strtoupper(Helper::proofingIdToName($row['proofing'])).'</span>';
                        // return $return;
                    }) 
                    // ->editColumn('board',function ($row){

                    //         switch(Helper::boardToName($row['board'])){
                    //             case "Irregular":
                    //                 $class = "bg-success";
                    //                 break;
                    //             case "Regular":
                    //                 $class = "bg-info";
                    //                 break;
                    //             case "None":
                    //                 $class = "bg-primary";
                    //                 break;    
                    //         }

                    //     return '<span class="badge '.$class.'">'.strtoupper(Helper::boardToName($row['board'])).'</span>';
                    //     // return $return;
                    // }) 
                     ->editColumn('is_local',function ($row){

                            switch(Helper::qualityIdToName($row['quality'])){
                                case "Local":
                                    $class = "bg-success";
                                    break;
                                case "Export":
                                    $class = "bg-info";
                                    break;  
                            }

                        return '<span class="badge '.$class.'">'.strtoupper(Helper::qualityIdToName($row['quality'])).'</span>';
                        // return $return;
                    })
                    ->rawColumns(['image', 'action'])

resources/views/customers/action.blade.php
<!-- <a href=""><i class="fas fa-eye" style="color: darkblue"></i></a> -->
<a href="{{ route('customers.edit',$id) }}"><i class="fas fa-pen" style="color: brown"></i></a>

resources/views/customers/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Create Customer</h3>
            </div>
            <form method="post" action="{{ route('customers.store') }}" enctype="multipart/form-data">
               @csrf
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Customer Name</label>
                        <input name="name" placeholder="customer name" class="form-control" type="text" required>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Company Name</label>
                        <input name="company_name" placeholder="company name" class="form-control" type="text" required>
                     </div>
                  </div>
                 
               </div>
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Mobile</label>
                        <input name="mobile" placeholder="Enter Phone No" class="form-control" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);"type = "number" maxlength = "11" required>
                     </div>
                  </div>
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Email</label>
                        <input name="email" placeholder="email" class="form-control" type="email" required>
                     </div>
                  </div>

                 
               </div> 
               <div class="row">
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                           <textarea name="description" class="form-control" placeholder="Description"></textarea>
                     </div>
                  </div>   
                 
               </div>               

               <button class="btn btn-success">Create</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/customers/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Edit Customer</h3>
            </div>
            <form method="POST" action="{{ route('customers.update', $customer->id) }}" enctype="multipart/form-data">
               {{csrf_field()}}
               {{method_field('PUT')}}
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>customer Name</label>
                        <input name="name" placeholder="customer name" value="{{$customer->name}}" class="form-control" type="text" required>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Company Name</label>
                        <input name="company_name" value="{{$customer->company_name}}" placeholder="company name" class="form-control" type="text" required>
                     </div>
                  </div>
                 
               </div>
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Mobile</label>
                        <input name="mobile" value="{{$customer->mobile}}" placeholder="phone no" class="form-control" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" type = "number" maxlength = "11" required>
                     </div>
                  </div>
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Email</label>
                        <input name="email" value="{{$customer->email}}" placeholder="email" class="form-control" type="email" required>
                     </div>
                  </div>
                   <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                      <textarea name="description" class="form-control" placeholder="Description">{{ ucfirst($customer->description) }}</textarea>  
                     </div>
                  </div> 
                   
               </div>            
                <input type="hidden" name="customer_id" value="{{$customer->id}}">
               <button class="btn btn-success">Update</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/customers/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Customers</h1>
@stop

@section('content')
    {{$dataTable->table()}}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.0.3/css/buttons.dataTables.min.css">
 <script src="https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.min.js"></script>

     <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
{{$dataTable->scripts()}}


<script src="{{asset('js/axios.min.js')}}"></script>
    <script>
        $(document).ready(function (){

            window.LaravelDataTables["customers-table"].on('draw', function(){

                $('.bt-toggle').bootstrapToggle();

            });
        })

        // send user's status update request
        function updateUserStatus(el){

            let id      = $(el).data('id');
           

            let status;

            if($(el).is(':checked')) {
                status = 'active';
            } else{
                status = 'deactivate';
            }

            if(id > 0){
                let url =  "/customer/update-status"
                console.log(id)
                console.log(status)
                axios.post(url,{id: id, status: status})
                    .then(function(response){
                    	console.log(response.data)
                        
                        if(response.data.error){
                              alertify.error('Error message');

                        }else{
                            alertify.success('customers  '+status+'  successfully');

                        }
                    })
                    .catch(function(error){
                        console.log(error)
                    })
            }
        }
    </script>
@stop

resources/views/customers/users.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1 style="text-align: center;">Add Costing</h1>
@stop

@section('content')
  

<div class="container">
<div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
           <!--  <div class="heading-panel">
               <h3 class="main-title text-left">Create Product</h3>
            </div> -->
            <form id="my-form" method="post" action="{{route('store-costing')}}" enctype="multipart/form-data">
               @csrf
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Company Name</label>
                        <select class="customer-select form-control" required name="customer_id">
                        <option disabled="disabled" selected="selected">Select Company </option>
                           @foreach(Helper::customers() as $c)
                           <option value="{{$c['id']}}" >
                              {{$c['company_name']}}
                           </option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Product Name</label>
                        <div id="product_parent">
                            <select class="product-select form-control" name="product_id">
                              <option disabled="disabled" selected="selected">Select Product </option>
                              @foreach(Helper::products() as $p)
                                  <option value="{{$p['id']}}" >
                                      {{$p['name_ar']}}
                                  </option>
                              @endforeach
                            </select>
                            
                          </div> 
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Type</label>
                        <select id="type" name="type" class="form-control" required>
                        <option disabled="disabled" selected="selected">Select Type</option>
                          <option value="0">Costing</option>
                          <option value="1">Proofing</option>
                          
                      </select>
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Quality </label>
                        <select id="quality" name="quality" class="form-control" required>
                          <option disabled="disabled" selected="selected">Select quality</option>
                          <option value="0">Local</option>
                          <option value="1">Export</option>
                          
                      </select>
                     </div>
                  </div>
                  
                 
               </div>             

               <button class="btn btn-success"onclick="return clicked();">Add Costing</button>
            </form>
         </div>
         <!-- Form -->
  </div>
    <h3>Apply Custom Filters</h3>
    <div class="row">
      <div class="col-sm-4">
        <input type="text" name="customer_id" class="form-control searchCompany" placeholder="Search for Company Only...">    
      </div>
      <div class="col-sm-4">
        <input type="text" name="product_id" class="form-control searchEmail" placeholder="Search for Product Only...">    
      </div>      
      <div class="col-sm-4">
        <input type="text" name="proofing" class="form-control searchName" placeholder="Search for Type Only in Upper Case...">    
      </div>
    </div>
    

 <!--    <select name="email" class="form-control searchEmail" placeholder="Search for Email Only...">
    <option value="" selected="selected" disabled="disabled">Select Bla</option>   
    <option value="usamairshad321@gmail.com">usamairshad321@gmail.com</option>
    <option value="asd@asd.com">asd@asd.com</option>
    <option value="super_admin@costing.com">super_admin@costing.com</option>
    </select> -->
    <br>
    <table class="table table-bordered data-table">

        <thead>

            <tr>

                <th>No</th>

                <th>Product</th>
                <th>Company</th>


                <th>Type</th>
                <!-- <th>Board Type</th> -->
                 <th>Quality</th>
                <th>image</th>

                <th width="100px">Action</th>
                <th width="100px">Edit</th>
                <th width="100px">History</th>

            </tr>

        </thead>

        <tbody>

        </tbody>

    </table>

</div>
@stop

@section('css')
<style type="text/css">
.table th {
  text-align: center;
}
.table tr {
  text-align: center;
}  
/*.col, .col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col-auto, .col-lg, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-auto, .col-md, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-md-auto, .col-sm, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-auto, .col-xl, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12, .col-xl-auto
{
  background-image: linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%);
}*/
</style>
@stop

@section('js')
<script src="{{ asset('js/customer-based-product.js') }}"></script>
<script type="text/javascript">
function clicked() {
      let price       = $('#type').val();
      let product       = $('#product_id').val();
      let quality       = $('#quality').val();


      if(price == 0)
      {
        price='Costing';
      }
      else if(price == 1)
      {
        price='Proofing';
      }
      if(quality == 0)
      {
        quality='Local';
      }
      else if(quality == 1)
      {
        quality='Export';
      }


    return confirm('Are you sure you want to add '+ price+' of '+ quality+ ' quality?');
}    
</script>

<script type="text/javascript">

  $(function () {

   

    var table = $('.data-table').DataTable({

        processing: true,

        serverSide: true,

        scrollX: false,


        ajax: {

          url: "{{ route('users.index') }}",

          data: function (d) {

                d.product_id = $('.searchEmail').val(),
                d.proofing = $('.searchName').val(),
                d.customer_id = $('.searchCompany').val(),

                d.search = $('input[type="search"]').val()

            }

        },

        columns: [

            {data: 'DT_RowIndex', name: 'DT_RowIndex'},

            {data: 'product_id', name: 'product_id'},

            {data: 'customer_id', name: 'customer_id'},

            {data: 'proofing', name: 'proofing'},

            // {data: 'board', name: 'board'},

            {data: 'is_local', name: 'is_local'},

            {data: 'image', name: 'image'},

            {data: 'action', name: 'action', orderable: false, searchable: false},

            {data: 'edit', name: 'edit', orderable: false, searchable: false},

            {data: 'history', name: 'history', orderable: false, searchable: false},
        ]

    });

   

    $(".searchEmail").keyup(function(){

        table.draw();

    });

    $(".searchName").keyup(function(){

        table.draw();

    }); 
    $(".searchCompany").keyup(function(){

        table.draw();

    });    

  

  });

</script>
@stop