routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function (){

    Route::get('add-costing', ['uses'=>'CustomerController@dummyIndex', 'as'=>'users.index']); // =========Dummy
	
    Route::get('/','ProductController@dashboard');
    Route::post('/filterizedproduct', 'ProductCostingController@filterizedProduct')->name('filterizedproduct');
	// Route::get('/', function(){
	// 	return view('welcome');
	// });

    // Route::get('/', 'CustomerController@test');
    // Route::get('add-costing', 'ProductCostingController@index');

    Route::resource('customers','CustomerController');
    Route::get('customer/{id}/delete','CustomerController@remove');
    Route::post('/customer/update-status', 'CustomerController@statusUpdated');

    Route::resource('vendors','VendorController');
    Route::get('vendor/{id}/delete','VendorController@remove');
    Route::get('/product-data/{id}','ProductCostingController@getDetails');
    Route::post('/vendor/update-status', 'VendorController@statusUpdated');

    Route::post('/store-costing', 'ProductCostingController@storeCosting')->name('store-costing');

    Route::resource('boards','BoardController');
    Route::resource('grammage','GrammageController');
    Route::get('/board/{id}/delete', 'BoardController@remove');
    Route::get('/vendor/{id}/delete', 'VendorController@remove');
    Route::get('/customer/{id}/delete', 'CustomerController@remove');
    Route::get('/grammage/{id}/delete', 'GrammageController@remove');

    Route::resource('products','ProductController')->middleware('optimizeImages');
    Route::get('product-costing/{id}/history', 'ProductCostingController@updatedCosting');



    // Route::get('addcosting','ProductController@addCosting'); 
    // Route::get('store-costing','ProductController@storeCosting')->name('storeCosting'); 

    Route::get('/customer/{id}/get-product', 'ProductController@getProduct');
    Route::get('/product/{id}/details', 'ProductCostingController@getDetails');
    Route::get('/product-history/{id}/details', 'ProductCostingController@getUpdatedDetails');
    Route::get('/product/{id}/delete', 'ProductController@remove');

    Route::get('/product/{id}/edit', 'ProductCostingController@editCosting');
    //Profile
    Route::group(['prefix' => 'profile'], function (){
        Route::get('',function(){
            return view('profile.index');
        });
        Route::get('change-password',function(){
            return view('profile.change-password');
        });
        Route::post('change_password','Auth\ForgotPasswordController@changePassword')->name('change_password');
    });
	
});

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
		'name',
		'customer_id',
		'image',
		'description',
	];

    public $table = "products";
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Http\Controllers\Controller as Controller;
use App\Http\Requests\StoreAdRequest;
use App\Models\Customers;
use App\Models\Products;
use App\Models\ProductImage;
use App\Models\Order;
use App\Models\ProductCosting;
use App\Models\ProductCostingUpdate;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use RealRashid\SweetAlert\Facades\Alert;
use App\DataTables\ProductsDataTable;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function dashboard(Request $request)
    {
        // dd("asdas");
        // // $tailor= ProductCosting::all();
        // $temp= DB::table('product_costing')
        //         ->join('product_costing_update','product_costing.id','product_costing_update.product_costing_id')
                
        //         ->select('product_costing_update.*','product_costing.product_id')
        //         ->orderBy('created_at','DESC')
        //         // ->distinct()
        //         ->latest()
        //         ->get();
        // $temp= DB::table('product_costing')
        //     ->join('product_costing_update', 'product_costing.id', '=', 'product_costing_update.product_costing_id')
        //     ->select('product_costing_update.*','product_costing.product_id')
        //     ->distinct('product_costing_update.product_costing_id')
        //     ->count();
         
           // $temp = DB::table('product_costing')
           //  ->join('product_costing_update', 'product_costing.id', '=', 'product_costing_update.product_costing_id')            
           //  ->select('product_costing_update.*','product_costing.product_id','product_costing.id as costing')
           //  ->groupBy('product_costing_id')
           //  ->get();

            // $temp= DB::table('product_costing_update')
            //       ->leftJoin('product_costing', 'product_costing_update.product_costing_id', '=', 'product_costing.id')
            //       ->orderBy('product_costing_update.created_at','DESC')
            //       ->get();

            // return $temp->groupBy('product_costing_id');

            $tailor = ProductCostingUpdate::whereRaw('Created_at IN (select MAX(Created_at) FROM product_costing_update GROUP BY PRODUCT_COSTING_ID)')->get();        
            
            // dd($data);   

        // $tailor=(array)$temp;
        
        $product= Products::select('name','id')->get();
        $filtered="no-filter";

        // return view('welcome',compact('tailor','product','filtered'));

        return view('dashboard',compact('tailor','product','filtered'));
    }


    public function index(ProductsDataTable $dataTable)
    {
        return $dataTable->render('products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customer= Customers::all();
        return view('products.create',compact('customer'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'file' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);
        $input = $request->except('image');
        $images = $request->file('image');
        $product = Products::create($input); 
        if($request->hasFile('image'))
        {
            foreach ($images as $image) {
                $input = $request->all();
                $imageName = time().'.'.$image->extension(); 
                $image->move('uploads/product-images', $imageName);
                $path = 'uploads/product-images/'.$imageName;
                $product_images = ProductImage::Create([
                    'product_id' => $product->id,
                    'path' => $path,
                ]);
            }
        }
        Alert::success('Product Created successfully');
        return redirect('products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $product=Products::where('id',$id)->first();
         $product->customer_id= Helper::customerIdToName($product->customer_id);
         $customer= Customers::all();
         return view('products.edit',compact('customer','product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        Products::where('id',$request['product_id'])->update(['name'=>$request['name'],'customer_id'=>$request['customer_id'],'description'=>$request['description']]);   
        
         if($request->hasFile('image'))
        {

            $input = $request->all();

            $image = $request->file('image');
            $imageName = time().'.'.$image->extension(); 
            $image->move('uploads/product-images', $imageName);
            
            Products::where('id',$input['product_id'])->update(['image'=>'uploads/product-images/'.$imageName]);   


        }
      
         Alert::success('Product updated successfully');
        return redirect('products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
    public function remove($id)
    {
        Products::where('id',$id)->delete();
        Alert::success('Product deleted successfully');
        return redirect('products');

    }
    public function getProduct($id)
    {
        $get_products = Products::where('customer_id',$id)->get();

        if(count($get_products) > 0){
            ?>
            <input name="dummy" class="form-control" type="hidden" value="found" />
            <select class="product-select form-control"  name="product_id">

               <option disabled="disabled" selected="selected">Product </option>>

              <?php 
              foreach($get_products as $product){ 

                echo '<option value="'.$product['id'].'" > '.$product['name'].'</option>';

                
                } 
                ?>
                  
            </select>
    
            <?php
        }else{
            echo '<input value="No Product Found" readonly name="product_id" type="text" /> 
                  <input name="dummy" class="form-control" type="hidden" value="not_found" />';
        }
    }
}

resources/views/products/action.blade.php
<!-- <a href=""><i class="fas fa-eye" style="color: darkblue"></i></a> -->
<a href="{{ route('products.edit',$id) }}"><i class="fas fa-pen" style="color: brown"></i></a>

resources/views/products/add-costing.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
 	@if($input['type'] == 0 && $input['quality'] == 1 )
		<span style="font-size: 30px">Export Costing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['type'] == 0 && $input['quality'] == 0)	
		<span style="font-size: 30px">Local Costing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['type'] == 1 && $input['quality'] == 0)	
		<span style="font-size: 30px">Local Proofing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['type'] == 1 && $input['quality'] == 1)	
		<span style="font-size: 30px">Export Proofing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>		
	@endif
@stop

@section('content')
	@if($input['type'] == 0 && $input['quality'] == 1 )
		<costing-export-component :costing="{{ json_encode($input) }}"></costing-export-component>
	@elseif($input['type'] == 0 && $input['quality'] == 0)	
		<costing-local-component :costing="{{ json_encode($input) }}"></costing-local-component>
	@elseif($input['type'] == 1 && $input['quality'] == 0)	
		<proofing-local-component :costing="{{ json_encode($input) }}"></proofing-local-component>
	@elseif($input['type'] == 1 && $input['quality'] == 1)	
		<proofing-export-component :costing="{{ json_encode($input) }}"></proofing-export-component>		
	@endif

@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/app.css"> -->
@stop

@section('js')

<!-- <script src="{{asset('js/axios.min.js')}}"></script>
<script src="{{asset('js/customer-based-product.js')}}"></script> -->

@stop

resources/views/products/costing.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
@stop

@section('content')
<div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
           <!--  <div class="heading-panel">
               <h3 class="main-title text-left">Create Product</h3>
            </div> -->
            <form id="my-form" method="post" action="{{route('store-costing')}}" enctype="multipart/form-data">
               @csrf
               <div class="row">

                @if(Auth::check())
                  <input type="hidden" name="created_by" value="{{Auth::user()->id}}">
                @endif
                  <!-- category_type --verified -->
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Company Name</label>
                        <select class="customer-select form-control" required name="customer_id">
                        <option disabled="disabled" selected="selected">Select Company </option>
                           @foreach(Helper::customers() as $c)
                           <option value="{{$c['id']}}" >
                              {{$c['company_name']}}
                           </option>
                           @endforeach
                        </select>
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Product Name</label>
                        <div id="product_parent">
                            <select class="product-select form-control" required name="product_id">
                              <option disabled="disabled" selected="selected">Select Product </option>
                              @foreach(Helper::products() as $p)
                                  <option value="{{$p['id']}}" >
                                      {{$p['name_ar']}}
                                  </option>
                              @endforeach
                            </select>
                            
                          </div> 
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Type</label>
                        <select id="type" name="type" class="form-control" required>
                        <option disabled="disabled" selected="selected">Select Type</option>
                          <option value="0">Costing</option>
                          <option value="1">Proofing</option>
                          
                      </select>
                     </div>
                  </div>
                  <div class="col-md-3 col-lg-3 col-xs-6 col-sm-6">
                     <div class="form-group">
                        <label>Quality </label>
                        <select id="quality" name="quality" class="form-control" required>
                          <option disabled="disabled" selected="selected">Select quality</option>
                          <option value="0">Local</option>
                          <option value="1">Export</option>
                          
                      </select>
                     </div>
                  </div>
                  
                 
               </div>             

               <button class="btn btn-success"onclick="return clicked();">Add Costing</button>
            </form>
         </div>
         <!-- Form -->
  </div>
  {{$dataTable->table()}}

    <style>
        #append-user-modal{ z-index: 9999 !important; }
    </style>
    <div class="modal fade" id="append-user-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">User Information</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" >
                    <div class="row">
                        <div class="col-md-12" id="append-user-data" ></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/app.css"> -->
@stop

@section('js')
{{$dataTable->scripts()}}
<script src="{{asset('js/axios.min.js')}}"></script>
<script src="{{ asset('js/load-admin-product-data.js') }}"></script>
<script src="{{ asset('js/customer-based-product.js') }}"></script>
<script type="text/javascript">
function clicked() {
      let price       = $('#type').val();
      let product       = $('#product_id').val();
      let quality       = $('#quality').val();

      if(price == 0)
      {
        price='Costing';
      }
      else if(price == 1)
      {
        price='Proofing';
      }
      if(quality == 0)
      {
        quality='Local';
      }
      else if(quality == 1)
      {
        quality='Export';
      }


    return confirm('Are you sure you want to add '+ price+' of '+ quality+ ' quality?');
}
</script>
<!-- <script type="text/javascript">
  // function add()
  // {
    //get the closable setting value.
    // var closable = alertify.alert().setting('closable');
    //grab the dialog instance using its parameter-less constructor then set multiple settings at once.
    // alertify.alert()
    //   .setting({
    //     'label':'Agree',
    //     'message': 'This dialog is : ' + (closable ? ' ' : ' not ') + 'closable.' ,
    //     'onok': function(){ alertify.success('Great');}
    //   }).show();;

  // }
$(document).ready( function() { // Wait until document is fully parsed
  $("#my-form").on('submit', function(e){

     e.preventDefault();

  });
})
</script> -->
@stop

resources/views/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Create Product</h3>
            </div>
            <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
               @csrf
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Company Name</label>
                        <select name="customer_id" class="form-control" required>
                        <option disabled="disabled" selected="selected">Select Company</option>
                          @foreach($customer as $c)
                              <option value="{{$c['id']}}" >
                                  {{$c['company_name']}}
                              </option>
                          @endforeach
                      </select>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label> Product Name</label>
                        <input name="name" placeholder="product name" class="form-control" type="text" required>
                     </div>
                  </div>
                 
               </div>
               <div class="row">
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Product Image</label>
                        <input name="image[]" placeholder="base image" class="form-control" type="file" multiple required>
                     </div>
                     
                  </div>   
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                           <textarea name="description" class="form-control" placeholder="Description"></textarea>
                     </div>
                  </div>

                 
               </div>               

               <button class="btn btn-success">Create</button>
            </form>
         </div>
         <!-- Form -->
  </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/products/edit-costing.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
 	@if($input['is_proofing'] == 0 && $input['is_local'] == 1 )
		<span style="font-size: 30px">Update Export Costing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['is_proofing'] == 0 && $input['is_local'] == 0)	
		<span style="font-size: 30px">Update Local Costing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['is_proofing'] == 1 && $input['is_local'] == 0)	
		<span style="font-size: 30px">Update Local Proofing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>
	@elseif($input['is_proofing'] == 1 && $input['is_local'] == 1)	
		<span style="font-size: 30px">Update Export Proofing Of </span><span style="font-size: 30px;color: #800080;font-weight: bold">{{App\Helpers\Helper::productIdToName($input['product_id'])}} </span>		
	@endif
@stop

@section('content')
	@if($input['is_proofing'] == 0 && $input['is_local'] == 1 )
		<costing-export-component-view :costing="{{ json_encode($input) }}" :temp="{{ json_encode($temp) }}"></costing-export-component-view>
	@elseif($input['is_proofing'] == 0 && $input['is_local'] == 0)	
		<costing-local-component-view :costing="{{ json_encode($input) }}" :temp="{{ json_encode($temp) }}"></costing-local-component-view>
	@elseif($input['is_proofing'] == 1 && $input['is_local'] == 0)	
		<proofing-local-component-view :costing="{{ json_encode($input) }}" :temp="{{ json_encode($temp) }}"></proofing-local-component-view>	
	@elseif($input['is_proofing'] == 1 && $input['is_local'] == 1)	
		<proofing-export-component-view :costing="{{ json_encode($input) }}" :temp="{{ json_encode($temp) }}"></proofing-export-component-view>		
	@endif

@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/app.css"> -->
@stop

@section('js')

<!-- <script src="{{asset('js/axios.min.js')}}"></script>
<script src="{{asset('js/customer-based-product.js')}}"></script> -->

@stop

resources/views/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Edit Product</h3>
            </div>
            <form method="POST" action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data">
               {{csrf_field()}}
               {{method_field('PUT')}}
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Customer Name</label>
                        <select name="customer_id" class="form-control" required>
                        <option disabled="disabled" selected="selected">{{$product->customer_id}}</option>
                          @foreach($customer as $c)
                              <option value="{{$c['id']}}" >
                                  {{$c['name']}}
                              </option>
                          @endforeach
                      </select>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Product Name</label>
                        <input name="name" value="{{$product->name}}" placeholder="company name" class="form-control" type="text" required>
                     </div>
                  </div>
                 
               </div>
               <div class="row">
                  <!-- category_type --verified -->
                   <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Description</label>
                     
                      <textarea name="description" class="form-control" placeholder="Description">{{ ucfirst($product->description) }}</textarea>  
                     </div>
                  </div> 
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Product Image</label>
                        <input name="image" placeholder="base image" class="form-control" type="file">
                     </div>
                      <div class="row">
                         <div class="col-md-3"><img class="thumbnail" height="100" src="{{ asset($product->image) }}" ></div>
                     </div>
                  </div>   
                   
               </div>            
                <input type="hidden" name="product_id" value="{{$product->id}}">
               <button class="btn btn-success">Update</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Products</h1>
@stop

@section('content')
    {{$dataTable->table()}}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
{{$dataTable->scripts()}}
@stop

resources/views/products/product-action.blade.php
<!-- <a href=""><i class="fas fa-eye" style="color: darkblue"></i></a> -->
<a href="#"><i class="fas fa-pen" style="color: brown"></i></a>

resources/views/products/product-data.blade.php
    <!-- Content Header (Page header) -->

	<div class="container-fluid col-md-12">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Customer</h3>
            </div>
            <!--; /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Quality</th>
                  <th>Board</th>
                  <th>Updated At</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                  <td>{{$data->name}}</td>
                  <td>{{$data->name}}</td>
                  <td>{{$data->name}}</td>
                  <td>{{$data->name}}</td>
                  <td>{{$data->name}}</td>
                </tr>
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
		
	</div>
	    <section class="content-header mt-n4">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-6">
                <img class="img-responsive" style="width: 370px; height: 350px" src="{{asset($data->image)}}" alt="Lights">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
@section('css')
<style type="text/css">
	.form-inline {
		display: block
	}
</style>	
@stop

resources/views/products/proofing-export-edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
@stop

@section('content')
  <h2>View</h2>
<proofing-export-component-view></proofing-export-component-view>

@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/app.css"> -->
@stop

@section('js')
{{$dataTable->scripts()}}
<script src="{{asset('js/axios.min.js')}}"></script>
<script src="{{ asset('js/load-admin-product-data.js') }}"></script>
<script src="{{ asset('js/customer-based-product.js') }}"></script>


@stop

resources/views/products/update-costing.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>History</h1>
@stop

@section('content')
    {{$dataTable->table()}}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
{{$dataTable->scripts()}}
@stop