routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function (){

    Route::get('add-costing', ['uses'=>'CustomerController@dummyIndex', 'as'=>'users.index']); // =========Dummy
	
    Route::get('/','ProductController@dashboard');
    Route::post('/filterizedproduct', 'ProductCostingController@filterizedProduct')->name('filterizedproduct');
	// Route::get('/', function(){
	// 	return view('welcome');
	// });

    // Route::get('/', 'CustomerController@test');
    // Route::get('add-costing', 'ProductCostingController@index');

    Route::resource('customers','CustomerController');
    Route::get('customer/{id}/delete','CustomerController@remove');
    Route::post('/customer/update-status', 'CustomerController@statusUpdated');

    Route::resource('vendors','VendorController');
    Route::get('vendor/{id}/delete','VendorController@remove');
    Route::get('/product-data/{id}','ProductCostingController@getDetails');
    Route::post('/vendor/update-status', 'VendorController@statusUpdated');

    Route::post('/store-costing', 'ProductCostingController@storeCosting')->name('store-costing');

    Route::resource('boards','BoardController');
    Route::resource('grammage','GrammageController');
    Route::get('/board/{id}/delete', 'BoardController@remove');
    Route::get('/vendor/{id}/delete', 'VendorController@remove');
    Route::get('/customer/{id}/delete', 'CustomerController@remove');
    Route::get('/grammage/{id}/delete', 'GrammageController@remove');

    Route::resource('products','ProductController')->middleware('optimizeImages');
    Route::get('product-costing/{id}/history', 'ProductCostingController@updatedCosting');



    // Route::get('addcosting','ProductController@addCosting'); 
    // Route::get('store-costing','ProductController@storeCosting')->name('storeCosting'); 

    Route::get('/customer/{id}/get-product', 'ProductController@getProduct');
    Route::get('/product/{id}/details', 'ProductCostingController@getDetails');
    Route::get('/product-history/{id}/details', 'ProductCostingController@getUpdatedDetails');
    Route::get('/product/{id}/delete', 'ProductController@remove');

    Route::get('/product/{id}/edit', 'ProductCostingController@editCosting');
    //Profile
    Route::group(['prefix' => 'profile'], function (){
        Route::get('',function(){
            return view('profile.index');
        });
        Route::get('change-password',function(){
            return view('profile.change-password');
        });
        Route::post('change_password','Auth\ForgotPasswordController@changePassword')->name('change_password');
    });
	
});

app/Models/Boards.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\BoardGramage;

class Boards extends Model
{
    protected $fillable = [
		'name',
		'vendor_id',
	];

    public $table = "boards";

    public function gramage() {
        return $this->hasMany('App\Models\BoardGramage');
    }
    
}

app/Http/Controllers/BoardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Helpers\Helper;
use App\Http\Controllers\Controller as Controller;
use App\Http\Requests\StoreAdRequest;
use App\Models\Vendors;
use App\Models\Boards;
use App\Models\BoardGramage;
use App\Models\Order;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use RealRashid\SweetAlert\Facades\Alert;
use App\DataTables\BoardsDataTable;

class BoardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(BoardsDataTable $dataTable)
    {
        return $dataTable->render('grammages.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $board= Boards::all();
        return view('grammages.create',compact('board'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input=$request->all();
        $grammage = Gramage::create($input);
        Alert::success('Board Created successfully');
        return redirect('boards');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    { 
        $gramage=BoardGramage::where('id',$id)->first();
        $board=Boards::where('id',$gramage->board_id)->first();
        // dd($gramage);
        $board->vendor_name= Helper::vendorIdToName($board->vendor_id);
        $vendor= Vendors::all();
        $boards= Boards::all();
        return view('boards.edit',compact('vendor','board','boards','gramage'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);   
        Boards::where('id',$request->board_id)->update(['name'=>$request->name,'vendor_id'=>$request->vendor_id]);
        BoardGramage::where('id',$request->board_gramage)->update(['gramage'=>$request->gramage,'per_kg_cost'=>$request->per_kg_cost]);
         Alert::success('Board updated successfully');
        return redirect('boards');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function getBoards(Request $request)
    {
        $boards=Boards::where('vendor_id',$request['id'])->get();
        return $boards;
    }
    public function getBoardDetails(Request $request)
    {
        $boards=Boards::where('id',$request['id'])->first();
        return $boards;   
    }

    public function getBoardGrammage(Request $request)
    {
        $boards=BoardGramage::where('board_id',$request['id'])->get();
        return $boards;   
    }
    
    public function getGrammagePrice(Request $request)
    {
        $boards=BoardGramage::where('id',$request['id'])->get();
        return $boards;
    }
    
    public function getIdGramage(Request $request)
    {
        $boards=BoardGramage::where('id',$request['id'])->value('gramage');
        return $boards;
    }
    public function remove($id)
    {
        BoardGramage::where('id',$id)->delete();
        Alert::success('Board deleted successfully');
        return redirect('boards');
    }
}

resources/views/boards/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Create Board</h3>
            </div>
            <form method="post" action="{{ route('boards.store') }}" enctype="multipart/form-data">
               @csrf
               <div class="row">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Vendor Name</label>
                        <select name="vendor_id" class="form-control" required>
                        <option disabled="disabled" selected="selected">Select Vendor</option>
                          @foreach($vendor as $c)
                              <option value="{{$c['id']}}" >
                                  {{$c['name']}}
                              </option>
                          @endforeach
                      </select>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  
                  <div  class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div id="billdesc" class="form-group">
                        <label> Board Name</label>
                        <input name="name" placeholder="board name" class="form-control" type="text" required>
                     </div>
                  </div>
                 
               </div>
               <button class="btn btn-success">Create</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <style type="text/css">
     #billdesc{
    padding-top: 0px;
}
#test{
    width: 100%;
    height: 35px;
}
option {
    height: 30px;
    line-height: 30px;
}

.editOption{
    width: 90%;
    height: 26px;
    position: relative;
    top: -29px;
    /*background: #E0F5FF;;*/
    border: 0;
    /*padding-left: 14px;*/
    margin-left: 10px;
} 
    </style>
@stop

@section('js')
<script type="text/javascript">
  var initialText = $('.editable').val();
$('.editOption').val(initialText);

$('#test').change(function(){
var selected = $('option:selected', this).attr('class');
var optionText = $('.editable').text();

if(selected == "editable"){
  $('.editOption').show();

  
  $('.editOption').keyup(function(){
      var editText = $('.editOption').val();
      $('.editable').val(editText);
      $('.editable').html(editText);
  });

}else{
  $('.editOption').hide();
}
});
</script>

@stop

resources/views/boards/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <!-- <h1>Dashboard</h1> -->
@stop

@section('content')

 <div class="col-md-12  col-sm-6 col-xs-12">
         <!--  Form -->
         <div class="form-grid">
            <div class="heading-panel">
               <h3 class="main-title text-left">Edit Board</h3>
            </div>
            <form method="POST" action="{{ route('boards.update', $board->id) }}" enctype="multipart/form-data">
               {{csrf_field()}}
               {{method_field('PUT')}}
               <div class="row">
                <input type="hidden" name="board_gramage" class="form-control" value="{{$gramage->id}}">
                  <!-- category_type --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Vendor Name</label>
                        <select name="vendor_id" class="form-control" required>
                        <option disabled="disabled" value="{{$board->vendor_id}}"  selected="selected">{{$board->vendor_name}}</option>
                          @foreach($vendor as $c)
                              <option value="{{$c['id']}}" >
                                  {{$c['name']}}
                              </option>
                          @endforeach
                      </select>
                     </div>
                  </div>
                  <!-- ad_link  --verified -->
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Board Name</label>
                        <!-- <input name="name" value="{{$board->name}}" placeholder="company name" class="form-control" type="text" required> -->
                        <select id="test" name="name" class="form-control" required>
                        <option  disabled="disabled" selected="selected">{{$board->name}}</option>
                          @foreach($boards as $c)
                              <option  value="{{$c['name']}}" >
                                  {{$c['name']}}
                              </option>
                              
                          @endforeach
                          <option  class="editable">Others</option>
                          
                         
                      </select>
                       <input class="form-control editOption" style="display:none;"></input>
                     </div>
                  </div>
                 
               </div>
               <div class="row">
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Gramage</label>
                        <input name="gramage" value="{{$gramage->gramage}}"  placeholder="gramage" class="form-control" type="number" step="any" min="0" max="10000" required>
                     </div>
                     
                  </div>   
                  <div class="col-md-6 col-lg-6 col-xs-12 col-sm-12">
                     <div class="form-group">
                        <label>Per Kg Cost</label>
                        <input name="per_kg_cost" value="{{$gramage->per_kg_cost}}" placeholder="per kg cost" class="form-control" type="number" step="any" min="0" max="10000" required>
                     </div>
                     
                  </div> 

                 
               </div>             
                <input type="hidden" name="board_id" value="{{$board->id}}">
               <button class="btn btn-success">Update</button>
            </form>
         </div>
         <!-- Form -->
      </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <style type="text/css">
     #billdesc{
    padding-top: 0px;
}
#test{
    width: 100%;
    height: 35px;
}
option {
    height: 30px;
    line-height: 30px;
}

.editOption{
    width: 30%;
    height: 26px;
    position: relative;
    top: -29px;
    /*background: #E0F5FF;;*/
    border: 0;
    /*padding-left: 14px;*/
    margin-left: 10px;
} 
    </style>
@stop

@section('js')
<script type="text/javascript">
  var initialText = $('.editable').val();
$('.editOption').val(initialText);

$('#test').change(function(){
var selected = $('option:selected', this).attr('class');
var optionText = $('.editable').text();

if(selected == "editable"){
  $('.editOption').show();

  
  $('.editOption').keyup(function(){
      var editText = $('.editOption').val();
      $('.editable').val(editText);
      $('.editable').html(editText);
  });

}else{
  $('.editOption').hide();
}
});
</script>

@stop

resources/views/boards/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Boards</h1>
@stop

@section('content')
    {{$dataTable->table()}}
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
{{$dataTable->scripts()}}
@stop